export const UI_SHELL_CHANNELS = Object.freeze({
  getSnapshot: 'ui-shell:get-snapshot',
  snapshotChanged: 'ui-shell:snapshot-changed',
  openSettings: 'ui-shell:open-settings',
  openContextMenu: 'ui-shell:open-context-menu',
  setBallVisible: 'ui-shell:set-ball-visible',
  setEdgeSnap: 'ui-shell:set-edge-snap',
  setTheme: 'ui-shell:set-theme',
  setSelectionEnabled: 'ui-shell:set-selection-enabled',
  setOcrActivation: 'ui-shell:set-ocr-activation',
  setTranslationEnabled: 'ui-shell:set-translation-enabled',
  setTranslationSourceLanguage: 'ui-shell:set-translation-source-language',
  setTranslationTargetLanguage: 'ui-shell:set-translation-target-language',
  getBaiduCredentialSummary: 'ui-shell:get-baidu-credential-summary',
  saveBaiduCredentials: 'ui-shell:save-baidu-credentials',
  deleteBaiduCredentials: 'ui-shell:delete-baidu-credentials',
  testTranslationProvider: 'ui-shell:test-translation-provider',
  openProviderPrivacyPolicy: 'ui-shell:open-provider-privacy-policy',
  openProviderServiceTerms: 'ui-shell:open-provider-service-terms',
  resetBallPosition: 'ui-shell:reset-ball-position',
  clearAllLocalData: 'ui-shell:clear-all-local-data'
} as const);
